server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crud_Spring"
    username: root
    password: vanlong1606
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "fOCOGfiWc3VYz3wZt2bngFxwKsbVgj9H1eSaSWdo42ayOw7bvI2VLAATU2SnDy4b"

logging:
  level:
    root: INFO
    com.example.Ecommerce: DEBUG




